security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPERADMIN:  ROLE_ADMIN

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                    
        fos_userbundle:
            id: fos_user.user_provider.username_email
            
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:   fos_user_security_logout
            anonymous:    true

    access_control:
        - { path: "^/[^/]+/login$", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/[^/]+/promos", role: ROLE_ADMIN }
        - { path: "^/[^/]+/stats", role: ROLE_ADMIN }
        - { path: "^/[^/]+/legal", role: ROLE_ADMIN }
        - { path: "^/[^/]+/view", role: ROLE_USER }
        - { path: "^/[^/]+/parrilla", role: ROLE_USER }
        - { path: "^/[^/]+/corporate", role: ROLE_USER }
        - { path: "^/[^/]+/live", role: ROLE_USER }
        - { path: "^/[^/]+/users", role: ROLE_ADMIN }        